### ISSUE TITLE
Option to show the popover at the top of the button.

### ISSUE THREAD

**Issue by kamilbeben** [saintplay/vue-swatches#13]
Hello.
I was looking for an option to show the popover at the top of the trigger button and i couldn't find it.
Is there something that i am missing, or this is not an option?
If so, would you accept pull request if i made one enabling this option?

**Comment by saintplay** [comment]
Hi,
Yes, there is no way right now to show the popover at the top of the trigger. Of course PRs are welcomed, but I wanna know more about the use case before implementing a solution. This is a problem related to mobile screen or don't having more space in the bottom of the screen? Can you show or explain why the popover should be opened a the top of the trigger, please?

**Comment by kamilbeben** [comment]
Second one, it's about not having enough space in the bottom of the screen. This screenshoot should explain what's in my mind.

![show-on-top-use-case](https://user-images.githubusercontent.com/20849474/43382541-58cff6d0-93d8-11e8-811f-98651e51772c.jpg)

**Comment by saintplay** [comment]
Ok, I see two possible solutions here:

1. Implement a new prop or refactor the existing `popover-to` to accept these values:
- `'bottom-right'` *default*
- `'bottom-left'`
- `'top-left'` **new**
- `'top-right'` **new**

2. Making the popover aware of the remaining space.

Bootstrap and Vuetify already do this, for example:

This Dropdown is intended to open up at the bottom of the button, and it does

 
| Before Clicking | After Clicking |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/9372893/43421935-c58f892c-940d-11e8-86c2-052d5c754815.png) | ![image](https://user-images.githubusercontent.com/9372893/43421148-7deb72ae-940b-11e8-9288-cfeaa3dbf4fd.png) |

However if there is no more space it open up from the bottom of the screen
 
| Before Clicking | After Clicking |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/9372893/43421847-7f3bbeaa-940d-11e8-8084-91d22d7220b0.png) | ![image](https://user-images.githubusercontent.com/9372893/43421858-87674158-940d-11e8-9bcb-8057ce58c98d.png) |

So this happens when there is no more space vertically, but the same goes if there is no more space horizontally.

So, I'm thinking the proper way to solve this issue, is making the popover aware of the screen space, and adding another prop like `popover-from`: `top`, or `bottom` (*default*).

What do you think?

**Comment by kamilbeben** [comment]
Surely, the second options seems much better. What would you say about using popper js? There already is [vue-js version of Popper js](https://github.com/RobinCK/vue-popper), and i've adjusted it's demo to cover our problem on [jsfiddle](https://jsfiddle.net/dha98peL/).

**Comment by saintplay** [comment]
I was aware of Popper and I really like it, however adding as a dependency to this project, will increment significantly the bundle size of this component,

I'm gonna implement the basic functionality I was talking about in the previous comment, if you want to use `popover.js` or `vue-popoverjs` you can do it, using the `inline-mode`

```
  <!-- same options, but placed on top -->
  <popper trigger="click" :options="{placement: 'bottom-end'}">
     <swatches v-model="color" inline />
  </popper>
```

**Comment by kamilbeben** [comment]
Okay, thank you for your help.

**Comment by erodewald** [comment]
Tangentially related - I think a killer feature would be _auto_ placement (wherever there is room) with a preference to a certain location.

**Comment by saintplay** [comment]
Yes, that is exactly what I meant

**Comment by erodewald** [comment]
@saintplay I missed that bit -- that's great, I look forward to that.

**Comment by saintplay** [comment]
Vue Swatches 2 is finally out, it have *always-on-screen* functionality for the popover.
You can check it here https://github.com/saintplay/vue-swatches/releases/tag/v2.0.0
